# Generated by Django 2.2.17 on 2020-12-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommenditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='ブランド名')),
                ('product', models.CharField(max_length=100, verbose_name='製品名')),
                ('content', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('item', models.CharField(max_length=100, verbose_name='アイテムの種類')),
                ('price', models.CharField(max_length=100, verbose_name='本体価格')),
                ('price_data', models.IntegerField(default=1000, verbose_name='価格データ')),
                ('age', models.IntegerField(default=10, verbose_name='年齢')),
                ('skintype', models.CharField(max_length=100, verbose_name='肌タイプ')),
                ('acne_point', models.IntegerField(default=0, verbose_name='ニキビポイント')),
                ('pores_point', models.IntegerField(default=0, verbose_name='毛穴ポイント')),
                ('spots_point', models.IntegerField(default=0, verbose_name='シミポイント')),
                ('wrinkle_point', models.IntegerField(default=0, verbose_name='シワポイント')),
                ('official_page', models.URLField(verbose_name='公式URL')),
                ('rakuten_page', models.URLField(verbose_name='楽天URL')),
                ('amazon_page', models.URLField(verbose_name='アマゾンURL')),
                ('trouble_name1', models.CharField(blank=True, max_length=100, verbose_name='ニキビ')),
                ('trouble_name2', models.CharField(blank=True, max_length=100, verbose_name='毛穴')),
                ('trouble_name3', models.CharField(blank=True, max_length=100, verbose_name='シワ')),
                ('trouble_name4', models.CharField(blank=True, max_length=100, verbose_name='シミ')),
                ('capacity', models.CharField(max_length=100, verbose_name='容量')),
            ],
        ),
    ]
