# Generated by Django 2.2.17 on 2020-12-09 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_price_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='ブランド名')),
                ('product', models.CharField(max_length=100, verbose_name='製品名')),
                ('comment', models.TextField(verbose_name='クチコミ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='イメージ画像')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='カテゴリー')),
                ('price', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Price', verbose_name='プライス')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Score', verbose_name='おすすめ度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
