# Generated by Django 2.2.17 on 2020-12-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenditem',
            name='spots_point',
        ),
        migrations.AddField(
            model_name='recommenditem',
            name='beard_point',
            field=models.IntegerField(default=0, verbose_name='髭剃り負けポイント'),
        ),
        migrations.AlterField(
            model_name='recommenditem',
            name='trouble_name4',
            field=models.CharField(blank=True, max_length=100, verbose_name='髭剃り負け'),
        ),
    ]
