# Generated by Django 2.2.17 on 2020-12-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201218_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenditem',
            name='age',
        ),
    ]
