# Generated by Django 2.2.17 on 2020-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_recommenditem_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenditem',
            name='beard_point',
        ),
        migrations.AddField(
            model_name='recommenditem',
            name='age',
            field=models.IntegerField(default=10, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='recommenditem',
            name='spots_point',
            field=models.IntegerField(default=0, verbose_name='シミポイント'),
        ),
        migrations.AlterField(
            model_name='recommenditem',
            name='trouble_name4',
            field=models.CharField(blank=True, max_length=100, verbose_name='シミ'),
        ),
    ]
